ASCIIGlyphs               ; Starts at 0x20
         dw    glyph_SPC  ;20
         dw    glyph_SPC  ;21
         dw    glyph_SPC  ;22
         dw    glyph_SPC  ;23
         dw    glyph_SPC  ;24
         dw    glyph_SPC  ;25
         dw    glyph_SPC  ;26
         dw    glyph_SPC  ;27
         dw    glyph_SPC  ;28
         dw    glyph_SPC  ;29
         dw    glyph_Asterisk ;2A
         dw    glyph_SPC  ;2B
         dw    glyph_SPC  ;2C
         dw    glyph_SPC  ;2D
         dw    glyph_Period ;2E
         dw    glyph_SPC  ;2F
         dw    glyph_0    ;30
         dw    glyph_1    ;31
         dw    glyph_2    ;32
         dw    glyph_3    ;33
         dw    glyph_4    ;34
         dw    glyph_5    ;35
         dw    glyph_6    ;36
         dw    glyph_7    ;37
         dw    glyph_8    ;38
         dw    glyph_9    ;39
         dw    glyph_SPC  ;3A
         dw    glyph_SPC  ;3B
         dw    glyph_SPC  ;3C
         dw    glyph_SPC  ;3D
         dw    glyph_SPC  ;3E
         dw    glyph_Question ;3F
         dw    glyph_SPC  ;40
AlphaGlyphs               ; Starts at 0x41.
         dw    glyph_A
         dw    glyph_B
         dw    glyph_C
         dw    glyph_D
         dw    glyph_E
         dw    glyph_F
         dw    glyph_G
         dw    glyph_H
         dw    glyph_I
         dw    glyph_J
         dw    glyph_K
         dw    glyph_L
         dw    glyph_M
         dw    glyph_N
         dw    glyph_O
         dw    glyph_P
         dw    glyph_Q
         dw    glyph_R
         dw    glyph_S
         dw    glyph_T
         dw    glyph_U
         dw    glyph_V
         dw    glyph_W
         dw    glyph_X
         dw    glyph_Y
         dw    glyph_Z


glyph_A  hex 000FF000
         hex   00F00F00
         hex   0F0000F0
         hex   0FFFFFF0
         hex   0F0000F0
         hex   0F0000F0

glyph_B hex 0FFFFF00
         hex 0F0000F0
         hex 0FFFFF00
         hex 0F0000F0
         hex 0F0000F0
         hex 0FFFFF00

glyph_C  hex 00FFFFF0
         hex 0F000000
         hex 0F000000
         hex 0F000000
         hex 0F000000
         hex 00FFFFF0

glyph_D  hex 0FFFFF00
         hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0
         hex 0FFFFF00

glyph_E  hex 0FFFFFF0
         hex 0F000000
         hex 0FFFF000
         hex 0F000000
         hex 0F000000
         hex 0FFFFFF0

glyph_F  hex 0FFFFFF0
         hex 0F000000
         hex 0FFFF000
         hex 0F000000
         hex 0F000000
         hex 0F000000

glyph_G  hex 00FFFFF0
         hex 0F000000
         hex 0F000000
         hex 0F00FFF0
         hex 0F0000F0
         hex 00FFFF00

glyph_H  hex 0F0000F0
         hex 0F0000F0
         hex 0FFFFFF0
         hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0

glyph_I  hex 0FFFFF00
         hex 000F0000
         hex 000F0000
         hex 000F0000
         hex 000F0000
         hex 0FFFFF00

glyph_J  hex 000000F0
         hex 000000F0
         hex 000000F0
         hex 0F0000F0
         hex 0F0000F0
         hex 00FFFF00

glyph_K  hex 0F000F00
         hex 0F00F000
         hex 0FFF0000
         hex 0F00F000
         hex 0F000F00
         hex 0F000F00

glyph_L  hex 0F000000
         hex 0F000000
         hex 0F000000
         hex 0F000000
         hex 0F000000
         hex 0FFFFFF0

glyph_M  hex 0F0000F0
         hex 0FF00FF0
         hex 0F0FF0F0
         hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0

glyph_N  hex 0F0000F0
         hex 0FF000F0
         hex 0F0F00F0
         hex 0F00F0F0
         hex 0F000FF0
         hex 0F0000F0

glyph_O  hex 00FFFF00
         hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0
         hex 00FFFF00

glyph_P  hex 0FFFFF00
         hex 0F0000F0
         hex 0FFFFF00
         hex 0F000000
         hex 0F000000
         hex 0F000000

glyph_Q  hex 00FFFF00
         hex 0F0000F0
         hex 0F0000F0
         hex 0F00F0F0
         hex 0F000FF0
         hex 00FFFFF0

glyph_R  hex 0FFFFF00
         hex 0F0000F0
         hex 0FFFFF00
         hex 0F000F00
         hex 0F0000F0
         hex 0F0000F0

glyph_S  hex 00FFFFF0
         hex 0F000000
         hex 00FFFF00
         hex 000000F0
         hex 000000F0
         hex 0FFFFF00

glyph_T  hex 0FFFFF00
         hex 000F0000
         hex 000F0000
         hex 000F0000
         hex 000F0000
         hex 000F0000

glyph_U  hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0
         hex 00FFFF00

glyph_V  hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0
         hex 00F00F00
         hex 000FF000

glyph_W  hex 0F0000F0
         hex 0F0000F0
         hex 0F0000F0
         hex 0F0FF0F0
         hex 0FF00FF0
         hex 0F0000F0

glyph_X  hex 0F0000F0
         hex 00F00F00
         hex 000FF000
         hex 000FF000
         hex 00F00F00
         hex 0F0000F0

glyph_Y  hex F00000F0
         hex 0F000F00
         hex 00F0F000
         hex 000F0000
         hex 000F0000
         hex 000F0000

glyph_Z  hex 0FFFFFF0
         hex 00000F00
         hex 0000F000
         hex 000F0000
         hex 00F00000
         hex   0FFFFFF0

glyph_SPC hex  00000000
         hex   00000000
         hex   00000000
         hex   00000000
         hex   00000000
         hex   00000000

**************************************************

glyph_Asterisk
         hex   00000000
         hex   00F0F0F0
         hex   000FFF00
         hex   00FFFFF0
         hex   000FFF00
         hex   00F0F0F0

glyph_Period
         hex   00000000
         hex   00000000
         hex   00000000
         hex   00000000
         hex   0000FF00
         hex   0000FF00

glyph_0  hex   00FFFF00
         hex   0F000FF0
         hex   0F00F0F0
         hex   0F0F00F0
         hex   0FF000F0
         hex   00FFFF00

glyph_1  hex   000F0000
         hex   00FF0000
         hex   000F0000
         hex   000F0000
         hex   000F0000
         hex   00FFF000

glyph_2  hex   00FFFF00
         hex   0F0000F0
         hex   00000F00
         hex   000FF000
         hex   00F00000
         hex   0FFFFFF0

glyph_3  hex   00FFFF00
         hex   000000F0
         hex   000FFF00
         hex   000000F0
         hex   000000F0
         hex   00FFFF00

glyph_4  hex   0000FF00
         hex   000F0F00
         hex   00F00F00
         hex   0FFFFFF0
         hex   00000F00
         hex   00000F00

glyph_5  hex   0FFFFFF0
         hex   0F000000
         hex   0FFFFF00
         hex   000000F0
         hex   0F0000F0
         hex   00FFFF00

glyph_6  hex   000FFF00
         hex   00F00000
         hex   0F000000
         hex   0FFFFF00
         hex   0F0000F0
         hex   00FFFF00

glyph_7  hex   0FFFFFF0
         hex   000000F0
         hex   00000F00
         hex   0000F000
         hex   000F0000
         hex   000F0000

glyph_8  hex   00FFFF00
         hex   0F0000F0
         hex   00FFFF00
         hex   0F0000F0
         hex   0F0000F0
         hex   00FFFF00

glyph_9  hex   00FFFF00
         hex   0F0000F0
         hex   00FFFF00
         hex   0000F000
         hex   000F0000
         hex   00F00000

glyph_Question
         hex   00FFF000
         hex   0F000F00
         hex   00000F00
         hex   000FF000
         hex   00000000
         hex   000FF000
